### ISSUE TITLE
Wrong obstacle highlighting

### ISSUE THREAD

**Issue by seangrant82** [Esri/aviation-approach-profiler#3]
When you display the profile of a runway that has obstacles then click a runway that doesn't, the obstacle on the other runway are highlighted when moving across profile view

need to add:  _this.obsObjects = [];_ in runwayProfile.js at line 716.

**Comment by jainamit1508** [comment]
Issue resolved by following commit c4326bbacfe438135ffa98e7494e2faf917d03f8
